[package]
name = "ail-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ail-conformance = { path = "../ail-conformance", version = "=0.5.0" }
ail-diagnostic = { path = "../ail-diagnostic", version = "=0.5.0" }
ail-provider = { path = "../ail-provider", version = "=0.5.0" }
ail-service = { path = "../ail-service", version = "=0.5.0" }
ail-store = { path = "../ail-store", version = "=0.5.0" }
ail-syntax = { path = "../ail-syntax", version = "=0.5.0" }
serde_json.workspace = true
