#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum FormContext {
    Expression,
    TopLevel,
    Type,
    Schema,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct FormHelp {
    pub(super) name: &'static str,
    pub(super) kind: &'static str,
    pub(super) minimum_version: u8,
    pub(super) syntax: &'static str,
    pub(super) summary: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct PrimitiveHelp {
    pub(super) name: &'static str,
    pub(super) minimum_version: u8,
    pub(super) signature: &'static str,
    pub(super) summary: &'static str,
    pub(super) effects: &'static str,
    pub(super) requirement: Option<&'static str>,
    pub(super) metering: Option<&'static str>,
}

pub(super) fn form_help(context: FormContext, name: &str) -> Option<FormHelp> {
    let catalog = match context {
        FormContext::Expression => EXPRESSION_FORMS,
        FormContext::TopLevel => TOP_LEVEL_FORMS,
        FormContext::Type => TYPE_FORMS,
        FormContext::Schema => SCHEMA_FORMS,
    };
    catalog.iter().copied().find(|entry| entry.name == name)
}

pub(super) fn primitive_help(name: &str) -> Option<PrimitiveHelp> {
    PRIMITIVES.iter().copied().find(|entry| entry.name == name)
}

const EXPRESSION_FORMS: &[FormHelp] = &[
    FormHelp {
        name: "quote",
        kind: "special form",
        minimum_version: 1,
        syntax: "(quote DATUM) or 'DATUM",
        summary: "Returns a datum as data without evaluating calls or variable references inside it.",
    },
    FormHelp {
        name: "if",
        kind: "special form",
        minimum_version: 1,
        syntax: "(if CONDITION THEN ELSE)",
        summary: "Evaluates exactly one branch. Only #f is false; 0, empty strings, Nil, and empty lists are truthy.",
    },
    FormHelp {
        name: "and",
        kind: "short-circuit special form",
        minimum_version: 2,
        syntax: "(and EXPRESSION...)",
        summary: "Evaluates left to right and returns the first #f or the final value. Empty and returns #t.",
    },
    FormHelp {
        name: "or",
        kind: "short-circuit special form",
        minimum_version: 2,
        syntax: "(or EXPRESSION...)",
        summary: "Evaluates left to right and returns the first truthy value. Empty or returns #f.",
    },
    FormHelp {
        name: "cond",
        kind: "short-circuit special form",
        minimum_version: 2,
        syntax: "(cond (CONDITION EXPRESSION)... (else EXPRESSION))",
        summary: "Tests clauses in source order and requires one explicit final else clause.",
    },
    FormHelp {
        name: "match",
        kind: "pattern-matching special form",
        minimum_version: 3,
        syntax: "(match VALUE (PATTERN EXPRESSION)... (_ EXPRESSION))",
        summary: "Evaluates VALUE once, checks arms in order, and scopes pattern bindings to one arm. A final _ arm is required.",
    },
    FormHelp {
        name: "let",
        kind: "lexical binding special form",
        minimum_version: 1,
        syntax: "(let ((NAME EXPRESSION)...) BODY)",
        summary: "Evaluates bindings from left to right. Later bindings can reference earlier bindings.",
    },
    FormHelp {
        name: "fn",
        kind: "function special form",
        minimum_version: 1,
        syntax: "(fn (PARAMETER...) BODY)",
        summary: "Creates a lexical closure. Calls check arity and recursion remains bounded by fuel and call depth.",
    },
    FormHelp {
        name: "do",
        kind: "sequencing special form",
        minimum_version: 1,
        syntax: "(do EXPRESSION EXPRESSION...)",
        summary: "Evaluates expressions from left to right and returns the final value. It does not bypass capability checks.",
    },
];

const TOP_LEVEL_FORMS: &[FormHelp] = &[
    FormHelp {
        name: "program",
        kind: "program root",
        minimum_version: 1,
        syntax: "(program FORM...)",
        summary: "Contains one complete, hashable Yanshu program. It is the canonical executable source form.",
    },
    FormHelp {
        name: "name",
        kind: "program declaration",
        minimum_version: 1,
        syntax: "(name MODULE)",
        summary: "Declares the logical module name used by linking and review tooling.",
    },
    FormHelp {
        name: "version",
        kind: "language-version declaration",
        minimum_version: 1,
        syntax: "(version 1|2|3|4)",
        summary: "Selects language semantics. Features from newer versions must fail closed.",
    },
    FormHelp {
        name: "capabilities",
        kind: "authority declaration",
        minimum_version: 1,
        syntax: "(capabilities NAME...)",
        summary: "Declares the maximum host authority this program may request; it does not inject a host by itself.",
    },
    FormHelp {
        name: "libraries",
        kind: "library contract declaration",
        minimum_version: 1,
        syntax: "(libraries (NAME VERSION)...)",
        summary: "Selects trusted versioned Library Backend contracts. It does not grant capabilities or load arbitrary code.",
    },
    FormHelp {
        name: "imports",
        kind: "module dependency declaration",
        minimum_version: 3,
        syntax: "(imports MODULE...)",
        summary: "Declares direct sealed-module dependencies. It never reads paths or performs dynamic loading.",
    },
    FormHelp {
        name: "schema",
        kind: "schema declaration",
        minimum_version: 1,
        syntax: "(schema NAME SPECIFICATION)",
        summary: "Defines a bounded declarative validator. Validation consumes fuel and rejects undeclared object fields.",
    },
    FormHelp {
        name: "data",
        kind: "closed data declaration",
        minimum_version: 3,
        syntax: "(data TYPE (CONSTRUCTOR FIELD...)...)",
        summary: "Defines a closed user type and fixed-arity constructors. Language v4 requires typed fields.",
    },
    FormHelp {
        name: "export-types",
        kind: "type export declaration",
        minimum_version: 4,
        syntax: "(export-types TYPE...)",
        summary: "Explicitly exports nominal types for sealed cross-module signatures.",
    },
    FormHelp {
        name: "signature",
        kind: "function type declaration",
        minimum_version: 4,
        syntax: "(signature NAME (fn (PARAMETER-TYPE...) RESULT-TYPE))",
        summary: "Declares a function boundary checked against inference before execution or sealing.",
    },
    FormHelp {
        name: "route",
        kind: "HTTP route declaration",
        minimum_version: 1,
        syntax: "(route METHOD PATH HANDLER)",
        summary: "Maps a bounded host HTTP route to an exported guest handler without granting network access.",
    },
    FormHelp {
        name: "def",
        kind: "global definition",
        minimum_version: 1,
        syntax: "(def NAME EXPRESSION)",
        summary: "Creates one immutable program-level binding. Recursive calls resolve through this binding.",
    },
    FormHelp {
        name: "export",
        kind: "value export declaration",
        minimum_version: 1,
        syntax: "(export NAME...)",
        summary: "Whitelists values visible to hosts and dependent sealed modules.",
    },
];

const TYPE_FORMS: &[FormHelp] = &[
    FormHelp {
        name: "fn",
        kind: "function type",
        minimum_version: 4,
        syntax: "(fn (PARAMETER-TYPE...) RESULT-TYPE)",
        summary: "Describes a callable value. Effects and capabilities are analyzed separately from its value type.",
    },
    FormHelp {
        name: "list",
        kind: "list type",
        minimum_version: 4,
        syntax: "(list ITEM-TYPE)",
        summary: "Describes an immutable homogeneous list value.",
    },
    FormHelp {
        name: "result",
        kind: "result type",
        minimum_version: 4,
        syntax: "(result SUCCESS-TYPE ERROR-TYPE)",
        summary: "Describes explicit recoverable business success or error data; it is not a general exception catcher.",
    },
];

const SCHEMA_FORMS: &[FormHelp] = &[
    FormHelp {
        name: "enum",
        kind: "schema form",
        minimum_version: 2,
        syntax: "(enum LITERAL...)",
        summary: "Accepts one of 1 to 64 unique integer, boolean, or string literals.",
    },
    FormHelp {
        name: "union",
        kind: "schema form",
        minimum_version: 2,
        syntax: "(union SCHEMA SCHEMA...)",
        summary: "Tries 2 to 8 bounded schema variants in source order and charges every attempted branch.",
    },
    FormHelp {
        name: "string",
        kind: "schema form",
        minimum_version: 1,
        syntax: "(string MINIMUM-LENGTH MAXIMUM-LENGTH)",
        summary: "Validates a string with explicit bounded Unicode-scalar length limits.",
    },
    FormHelp {
        name: "integer",
        kind: "schema form",
        minimum_version: 1,
        syntax: "(integer MINIMUM MAXIMUM)",
        summary: "Validates an arbitrary-precision integer inside optional inclusive bounds.",
    },
    FormHelp {
        name: "list",
        kind: "schema form",
        minimum_version: 1,
        syntax: "(list ITEM-SCHEMA MINIMUM-LENGTH MAXIMUM-LENGTH)",
        summary: "Validates every list item and enforces explicit collection bounds. Work is fuel-metered per item.",
    },
    FormHelp {
        name: "object",
        kind: "schema form",
        minimum_version: 1,
        syntax: "(object (required \"NAME\" SCHEMA)... (optional \"NAME\" SCHEMA [DEFAULT])...)",
        summary: "Validates declared fields, rejects extra fields, and normalizes optional defaults.",
    },
    FormHelp {
        name: "required",
        kind: "object schema field",
        minimum_version: 1,
        syntax: "(required \"NAME\" SCHEMA)",
        summary: "Declares an object field that must be present and satisfy its schema.",
    },
    FormHelp {
        name: "optional",
        kind: "object schema field",
        minimum_version: 1,
        syntax: "(optional \"NAME\" SCHEMA [DEFAULT])",
        summary: "Declares an optional object field and an optional schema-checked default.",
    },
];

const PRIMITIVES: &[PrimitiveHelp] = &[
    PrimitiveHelp {
        name: "+",
        minimum_version: 1,
        signature: "fn(Int...) -> Int",
        summary: "Adds all arguments from left to right. Empty addition returns 0.",
        effects: "pure",
        requirement: None,
        metering: Some("integer work and result size are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "*",
        minimum_version: 1,
        signature: "fn(Int...) -> Int",
        summary: "Multiplies all arguments. Empty multiplication returns 1.",
        effects: "pure",
        requirement: None,
        metering: Some("integer work and result size are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "-",
        minimum_version: 1,
        signature: "fn(Int, Int...) -> Int",
        summary: "Negates one integer or subtracts later integers from the first.",
        effects: "pure",
        requirement: None,
        metering: Some("integer work and result size are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "quotient",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Int",
        summary: "Performs integer division. Division by zero is a fail-loud runtime diagnostic.",
        effects: "pure",
        requirement: None,
        metering: Some("arbitrary-precision integer work is fuel-metered"),
    },
    PrimitiveHelp {
        name: "remainder",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Int",
        summary: "Returns the integer remainder. A zero divisor is a fail-loud runtime diagnostic.",
        effects: "pure",
        requirement: None,
        metering: Some("arbitrary-precision integer work is fuel-metered"),
    },
    PrimitiveHelp {
        name: "checked-quotient",
        minimum_version: 2,
        signature: "fn(Int, Int) -> Result<Int, Map>",
        summary: "Performs integer division and converts a zero divisor into explicit DIVIDE_BY_ZERO error data.",
        effects: "pure",
        requirement: None,
        metering: Some("arbitrary-precision integer work is fuel-metered"),
    },
    PrimitiveHelp {
        name: "checked-remainder",
        minimum_version: 2,
        signature: "fn(Int, Int) -> Result<Int, Map>",
        summary: "Computes a remainder and converts a zero divisor into explicit DIVIDE_BY_ZERO error data.",
        effects: "pure",
        requirement: None,
        metering: Some("arbitrary-precision integer work is fuel-metered"),
    },
    PrimitiveHelp {
        name: "=",
        minimum_version: 1,
        signature: "fn(Any, Any) -> Bool",
        summary: "Tests structural equality of bounded guest values.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "<",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Bool",
        summary: "Tests arbitrary-precision integer ordering.",
        effects: "pure",
        requirement: None,
        metering: Some("integer comparison work is bounded"),
    },
    PrimitiveHelp {
        name: "<=",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Bool",
        summary: "Tests arbitrary-precision integer ordering.",
        effects: "pure",
        requirement: None,
        metering: Some("integer comparison work is bounded"),
    },
    PrimitiveHelp {
        name: ">",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Bool",
        summary: "Tests arbitrary-precision integer ordering.",
        effects: "pure",
        requirement: None,
        metering: Some("integer comparison work is bounded"),
    },
    PrimitiveHelp {
        name: ">=",
        minimum_version: 1,
        signature: "fn(Int, Int) -> Bool",
        summary: "Tests arbitrary-precision integer ordering.",
        effects: "pure",
        requirement: None,
        metering: Some("integer comparison work is bounded"),
    },
    PrimitiveHelp {
        name: "not",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Returns #t only for #f. Every other guest value is truthy.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "integer?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is an arbitrary-precision integer.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "boolean?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is #t or #f.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "string?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is a bounded UTF-8 string.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "list?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is an immutable guest list.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "map?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is an immutable guest map.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "string-append",
        minimum_version: 1,
        signature: "fn(String...) -> String",
        summary: "Concatenates strings after checking the bounded output size.",
        effects: "pure",
        requirement: None,
        metering: Some("input and output string work is fuel-metered"),
    },
    PrimitiveHelp {
        name: "number->string",
        minimum_version: 2,
        signature: "fn(Int) -> String",
        summary: "Formats an arbitrary-precision integer in base-10 notation.",
        effects: "pure",
        requirement: None,
        metering: Some("digit conversion and output size are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "list",
        minimum_version: 1,
        signature: "fn(T...) -> List<T>",
        summary: "Constructs an immutable list while preserving argument order.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "list-map",
        minimum_version: 2,
        signature: "fn(fn(T) -> U, List<T>) -> List<U>",
        summary: "Calls the callback once per item and preserves input order and length.",
        effects: "callback-dependent",
        requirement: None,
        metering: Some("each visited item and callback evaluation consumes fuel"),
    },
    PrimitiveHelp {
        name: "list-filter",
        minimum_version: 2,
        signature: "fn(fn(T) -> Any, List<T>) -> List<T>",
        summary: "Keeps items whose callback result is truthy and preserves source order.",
        effects: "callback-dependent",
        requirement: None,
        metering: Some("each visited item and callback evaluation consumes fuel"),
    },
    PrimitiveHelp {
        name: "list-fold",
        minimum_version: 2,
        signature: "fn(fn(A, T) -> A, A, List<T>) -> A",
        summary: "Folds left to right by calling the callback with accumulator and item.",
        effects: "callback-dependent",
        requirement: None,
        metering: Some("each visited item and callback evaluation consumes fuel"),
    },
    PrimitiveHelp {
        name: "sum",
        minimum_version: 2,
        signature: "fn(List<Int>) -> Int",
        summary: "Adds every integer in a list. An empty list returns 0.",
        effects: "pure",
        requirement: None,
        metering: Some("each item and arbitrary-precision addition consumes fuel"),
    },
    PrimitiveHelp {
        name: "empty?",
        minimum_version: 1,
        signature: "fn(List<T>) -> Bool",
        summary: "Tests whether a list has no items.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "length",
        minimum_version: 1,
        signature: "fn(List<T>) -> Int",
        summary: "Returns a list length as an arbitrary-precision integer.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "first",
        minimum_version: 1,
        signature: "fn(List<T>) -> T",
        summary: "Returns the first list item. An empty list fails loudly.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "rest",
        minimum_version: 1,
        signature: "fn(List<T>) -> List<T>",
        summary: "Returns the list after its first item. An empty list fails loudly.",
        effects: "pure",
        requirement: None,
        metering: Some("the returned immutable list remains size-bounded"),
    },
    PrimitiveHelp {
        name: "map",
        minimum_version: 1,
        signature: "fn((MapKey, Any)...) -> Map",
        summary: "Constructs an immutable map from alternating key and value arguments.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "get",
        minimum_version: 1,
        signature: "fn(Map, MapKey) -> Any",
        summary: "Reads a map value. A missing key fails loudly.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "get-or",
        minimum_version: 1,
        signature: "fn(Map, MapKey, T) -> Any|T",
        summary: "Reads a map value or returns the supplied fallback when the key is absent.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "has-key?",
        minimum_version: 1,
        signature: "fn(Map, MapKey) -> Bool",
        summary: "Tests whether an immutable map contains a key.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "assoc",
        minimum_version: 1,
        signature: "fn(Map, MapKey, Any) -> Map",
        summary: "Returns a new map with one key associated to a value.",
        effects: "pure",
        requirement: None,
        metering: Some("copying and result size remain bounded"),
    },
    PrimitiveHelp {
        name: "ok",
        minimum_version: 1,
        signature: "fn(T) -> Result<T, E>",
        summary: "Constructs explicit recoverable success data.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "err",
        minimum_version: 1,
        signature: "fn(E) -> Result<T, E>",
        summary: "Constructs explicit recoverable business error data.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "ok?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is an Ok result.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "err?",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Tests whether a value is an Err result.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "result-value",
        minimum_version: 1,
        signature: "fn(Result<T, E>) -> T|E",
        summary: "Returns the payload from either an Ok or Err result.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "unwrap",
        minimum_version: 1,
        signature: "fn(Result<T, E>) -> T",
        summary: "Returns an Ok payload. An Err remains fail-loud and is not silently recovered.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "validate",
        minimum_version: 1,
        signature: "fn(Schema<T>, Any) -> Result<T, List<Map>>",
        summary: "Validates and normalizes bounded guest data, returning structured issues on failure.",
        effects: "pure",
        requirement: None,
        metering: Some("every visited schema/value node consumes fuel"),
    },
    PrimitiveHelp {
        name: "validate-report",
        minimum_version: 2,
        signature: "fn(Schema<T>, Any) -> Map",
        summary: "Returns normalized value, bounded issues, validity, and machine-readable validation cost.",
        effects: "pure",
        requirement: None,
        metering: Some("reports the same bounded schema fuel work it performs"),
    },
    PrimitiveHelp {
        name: "api-response",
        minimum_version: 1,
        signature: "fn(Int, Any) -> Map",
        summary: "Constructs a guest HTTP response value for host-side validation.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "api-error",
        minimum_version: 1,
        signature: "fn(Int, String, String[, Any]) -> Map",
        summary: "Constructs a stable-code guest HTTP error response with optional bounded details.",
        effects: "pure",
        requirement: None,
        metering: None,
    },
    PrimitiveHelp {
        name: "log",
        minimum_version: 1,
        signature: "fn(Any) -> Nil",
        summary: "Sends one bounded portable value to the explicitly injected host logger.",
        effects: "log",
        requirement: Some("(capabilities log) and an injected log host"),
        metering: Some("the call and returned portable value are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "now-ms",
        minimum_version: 1,
        signature: "fn() -> Int",
        summary: "Reads the explicitly injected host clock as Unix milliseconds.",
        effects: "clock",
        requirement: Some("(capabilities clock) and an injected clock host"),
        metering: Some("the capability call and returned portable value are fuel-metered"),
    },
    PrimitiveHelp {
        name: "kv-get",
        minimum_version: 1,
        signature: "fn(Any, Any) -> Any",
        summary: "Reads a key from the current host-owned transaction and returns a supplied fallback when absent.",
        effects: "kv",
        requirement: Some("(capabilities kv) and an injected transactional KV host"),
        metering: Some("the call and returned portable value are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "kv-put",
        minimum_version: 1,
        signature: "fn(Any, Any) -> Nil",
        summary: "Stages one key/value write in the current host-owned transaction.",
        effects: "kv",
        requirement: Some("(capabilities kv) and an injected transactional KV host"),
        metering: Some("the call and portable arguments are bounded and fuel-metered"),
    },
    PrimitiveHelp {
        name: "kv-delete",
        minimum_version: 1,
        signature: "fn(Any) -> Bool",
        summary: "Stages deletion of one key in the current host-owned transaction.",
        effects: "kv",
        requirement: Some("(capabilities kv) and an injected transactional KV host"),
        metering: Some("the capability call is fuel-metered"),
    },
    PrimitiveHelp {
        name: "kv-list",
        minimum_version: 1,
        signature: "fn(Any) -> List<Any>",
        summary: "Lists bounded transaction entries selected by the supplied host contract input.",
        effects: "kv",
        requirement: Some("(capabilities kv) and an injected transactional KV host"),
        metering: Some("the call and returned portable list are bounded and fuel-metered"),
    },
];

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::{EXPRESSION_FORMS, PRIMITIVES, SCHEMA_FORMS, TOP_LEVEL_FORMS, TYPE_FORMS};

    #[test]
    fn catalogs_have_unique_nonempty_entries() {
        for catalog in [EXPRESSION_FORMS, TOP_LEVEL_FORMS, TYPE_FORMS, SCHEMA_FORMS] {
            let mut names = BTreeSet::new();
            for entry in catalog {
                assert!(!entry.name.is_empty());
                assert!(!entry.syntax.is_empty());
                assert!(!entry.summary.is_empty());
                assert!(names.insert(entry.name));
            }
        }

        let mut primitive_names = BTreeSet::new();
        for primitive in PRIMITIVES {
            assert!(!primitive.signature.is_empty());
            assert!(!primitive.summary.is_empty());
            assert!(primitive_names.insert(primitive.name));
        }
    }
}
