[package]
name = "yanshu-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
yanshu-analysis = { path = "../yanshu-analysis", version = "=0.10.0" }
yanshu-compiler = { path = "../yanshu-compiler", version = "=0.10.0" }
yanshu-diagnostic = { path = "../yanshu-diagnostic", version = "=0.10.0" }
yanshu-library = { path = "../yanshu-library", version = "=0.10.0" }
yanshu-syntax = { path = "../yanshu-syntax", version = "=0.10.0" }
num-bigint.workspace = true
num-traits.workspace = true
serde_json.workspace = true
