import { copyFile, mkdir, rm } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const wikiRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const repositoryRoot = resolve(wikiRoot, '..')
const outputRoot = join(wikiRoot, 'public', 'source')

// These are snapshots of files linked by the language Wiki. Keep the list
// explicit so the build cannot publish credentials, runtime data, or unrelated
// implementation history.
const publishedFiles = [
  '.github/workflows/ci.yml',
  '.github/workflows/fuzz.yml',
  '.github/workflows/pages.yml',
  '.github/workflows/release.yml',
  'Cargo.lock',
  'Cargo.toml',
  'deny.toml',
  'conformance/v1/invalid/multiple-forms.yan',
  'conformance/v1/invalid/unknown-library.yan',
  'conformance/v1/manifest.json',
  'conformance/v1/programs/core.yan',
  'conformance/v1/programs/library.yan',
  'conformance/v1/programs/schema.yan',
  'docs/engineering/rust-safety-policy.md',
  'docs/engineering/rust-dependency-audit.md',
  'docs/engineering/git-workflow.md',
  'docs/engineering/release-supply-chain.md',
  'docs/operations/backup-restore.md',
  'docs/engineering/version-store-recovery.md',
  'docs/operations/shadow-rollout.md',
  'docs/archive/prototype/v0.1-language-spec.md',
  'docs/specs/v0.6.md',
  'docs/specs/v0.7.md',
  'docs/specs/v0.8.md',
  'docs/specs/v0.9.md',
  'docs/specs/v0.10.md',
  'docs/specs/v0.11.md',
  'docs/specs/v0.11-audit-closure.md',
  'docs/specs/v0.12.md',
  'docs/ai-agent-guide.md',
  'examples/discount/tests.json',
  'examples/discount/v1.yan',
  'examples/discount/v2.yan',
  'examples/libraries/tests.json',
  'examples/libraries/text.yan',
  'examples/tasks/scenarios.json',
  'examples/tasks/service.yan',
  'examples/expenses/scenarios.json',
  'examples/expenses/service.yan',
  'examples/bundles/expense-approval/app.yan',
  'examples/bundles/expense-approval/policy.yan',
  'examples/bundles/expense-approval/bundle.json',
  'examples/bundles/typed-expense/app.yan',
  'examples/bundles/typed-expense/policy.yan',
  'examples/bundles/typed-expense/bundle.json',
  'examples/packages/typed-expense/yanshu-package.source.json',
  'examples/packages/typed-expense/yanshu.lock.json',
  'examples/packages/typed-expense/app.yan',
  'examples/packages/typed-expense/packages/typed-policy/yanshu-package.source.json',
  'examples/packages/typed-expense/packages/typed-policy/policy.yan',
  'scripts/audit-rust.ps1',
  'scripts/check-doc-links.mjs',
  'scripts/check-repository-boundaries.ps1',
  'scripts/check.ps1',
  'scripts/serve-tasks.ps1',
  'scripts/wasm-smoke.mjs',
  'scripts/assemble-release.mjs',
  'scripts/build-release.mjs',
  'scripts/normalize-sbom.mjs',
  'scripts/release-lib.mjs',
  'scripts/release-metadata.mjs',
  'scripts/release.test.mjs',
  'scripts/verify-release.mjs',
  'fuzz/Cargo.toml',
  'fuzz/fuzz_targets/artifact_loaders.rs',
  'fuzz/fuzz_targets/boundary_inputs.rs',
  'fuzz/fuzz_targets/portable_value.rs',
  'fuzz/fuzz_targets/reader_parser.rs',
  'rust/crates/yanshu-cli/src/main.rs',
  'rust/crates/yanshu-bundle/src/graph.rs',
  'rust/crates/yanshu-bundle/src/lib.rs',
  'rust/crates/yanshu-bundle/src/linker.rs',
  'rust/crates/yanshu-bundle/src/manifest.rs',
  'rust/crates/yanshu-analysis/src/effects.rs',
  'rust/crates/yanshu-analysis/src/infer.rs',
  'rust/crates/yanshu-analysis/src/lib.rs',
  'rust/crates/yanshu-analysis/src/review.rs',
  'rust/crates/yanshu-analysis/src/types.rs',
  'rust/crates/yanshu-compiler/src/artifact.rs',
  'rust/crates/yanshu-compiler/src/bytecode.rs',
  'rust/crates/yanshu-compiler/src/compile.rs',
  'rust/crates/yanshu-compiler/src/lib.rs',
  'rust/crates/yanshu-compiler/src/verify.rs',
  'rust/crates/yanshu-compiler/src/wasm.rs',
  'rust/crates/yanshu-library/src/contract.rs',
  'rust/crates/yanshu-library/src/lib.rs',
  'rust/crates/yanshu-library/src/registry.rs',
  'rust/crates/yanshu-library/src/text.rs',
  'rust/crates/yanshu-library/src/value.rs',
  'rust/crates/yanshu-package/src/format.rs',
  'rust/crates/yanshu-package/src/lib.rs',
  'rust/crates/yanshu-package/src/model.rs',
  'rust/crates/yanshu-package/src/parse.rs',
  'rust/crates/yanshu-package/src/store.rs',
  'rust/crates/yanshu-conformance/src/lib.rs',
  'rust/crates/yanshu-diagnostic/src/lib.rs',
  'rust/crates/yanshu-http/src/lib.rs',
  'rust/crates/yanshu-http/src/auth.rs',
  'rust/crates/yanshu-http/src/config.rs',
  'rust/crates/yanshu-http/src/dispatch.rs',
  'rust/crates/yanshu-http/src/loader.rs',
  'rust/crates/yanshu-http/src/observation.rs',
  'rust/crates/yanshu-http/src/request.rs',
  'rust/crates/yanshu-http/src/response.rs',
  'rust/crates/yanshu-http/src/router.rs',
  'rust/crates/yanshu-http/src/shadow.rs',
  'rust/crates/yanshu-http/src/transport.rs',
  'rust/crates/yanshu-ops/src/lib.rs',
  'rust/crates/yanshu-ops/src/lease.rs',
  'rust/crates/yanshu-ops/src/manifest.rs',
  'rust/crates/yanshu-ops/src/operations.rs',
  'rust/crates/yanshu-provider/src/lib.rs',
  'rust/crates/yanshu-provider/src/agent.rs',
  'rust/crates/yanshu-rollout/src/comparison.rs',
  'rust/crates/yanshu-rollout/src/lib.rs',
  'rust/crates/yanshu-rollout/src/observation.rs',
  'rust/crates/yanshu-rollout/src/policy.rs',
  'rust/crates/yanshu-rollout/src/runtime.rs',
  'rust/crates/yanshu-runtime/src/budget.rs',
  'rust/crates/yanshu-runtime/src/compiled.rs',
  'rust/crates/yanshu-runtime/src/lib.rs',
  'rust/crates/yanshu-runtime/src/matcher.rs',
  'rust/crates/yanshu-runtime/src/schema.rs',
  'rust/crates/yanshu-runtime/src/value.rs',
  'rust/crates/yanshu-format/src/cst.rs',
  'rust/crates/yanshu-format/src/lib.rs',
  'rust/crates/yanshu-format/src/render.rs',
  'rust/crates/yanshu-lsp/src/document.rs',
  'rust/crates/yanshu-lsp/src/lib.rs',
  'rust/crates/yanshu-lsp/src/main.rs',
  'rust/crates/yanshu-lsp/src/protocol.rs',
  'rust/crates/yanshu-lsp/src/server.rs',
  'rust/crates/yanshu-service/src/lib.rs',
  'rust/crates/yanshu-server/src/main.rs',
  'rust/crates/yanshu-server/src/configuration.rs',
  'rust/crates/yanshu-store/src/lib.rs',
  'rust/crates/yanshu-store/src/events.rs',
  'rust/crates/yanshu-store/src/metadata.rs',
  'rust/crates/yanshu-store/src/recovery.rs',
  'rust/crates/yanshu-store/src/scenario.rs',
  'rust/crates/yanshu-store/src/storage.rs',
  'rust/crates/yanshu-store/src/store.rs',
  'rust/crates/yanshu-store/src/transaction.rs',
  'rust/crates/yanshu-syntax/src/ast.rs',
  'rust/crates/yanshu-syntax/src/lib.rs',
  'rust/crates/yanshu-syntax/src/node_id.rs',
  'rust/crates/yanshu-syntax/src/parser.rs',
  'rust/crates/yanshu-syntax/src/reader.rs'
]

// Recreate the generated mirror so removed allowlist entries cannot linger.
await rm(outputRoot, { recursive: true, force: true })

await Promise.all(
  publishedFiles.map(async (relativePath) => {
    const source = join(repositoryRoot, relativePath)
    const destination = join(outputRoot, `${relativePath}.txt`)
    await mkdir(dirname(destination), { recursive: true })
    await copyFile(source, destination)
  })
)

console.log(`Synced ${publishedFiles.length} repository files to the Wiki source mirror.`)
